install:
 - source ./texlive_install.sh
 
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    
script:
# Prefix command with travis_wait x so it times out after 3 mins
- travis_wait 3 pdflatex main.tex

notifications:
  email: false
